(define (solve l)
  (define (f n)
    (let ((_ (quotient (- l 1) n)))
      (quotient (* n _ (+ _ 1)) 2)))
  (- (+ (f 3)
        (f 5))
     (f 15)))

(let ((_ (solve 1000)))
  (print _) (assert (= _ 233168)))
