(define (main n)
  (let ((array (make-vector (add1 n) 0)))
    (let *main ((i 1))
      (unless (= i n)
        (do ((j i (+ j i))) ((> j n) (*main (add1 i)))
          (vector-set! array j (+ (vector-ref array j) (* i i))))))
    (do ((i 1 (add1 i))
         (acc 0 (if (integer? (sqrt (vector-ref array i)))
                    (+ acc i)
                    acc)))
      ((= i n) acc))))

(display (main 64000000))
(newline)
