(define (main n)
  (do ((x 0 (add1 x))
       (acc 0 (if (or (zero? (remainder x 3))
                      (zero? (remainder x 5)))
                  (+ acc x)
                  acc)))
    ((= x n) acc)))

(display (main 1000))
(newline)
