(define (main n)
  (do ((x 1 (add1 x))
       (acc 0 (+ acc (case (remainder x 4)
                       ((0 2) (* 20  (round (expt 30  (sub1 (quotient x 2))))))
                       ((1)   (* 100 (round (expt 500 (sub1 (quotient x 4))))))
                       (else 0)))))
    ((> x n) acc)))

(display (main 9))
(newline)
