(define (main n)
  (do ((i 1 (add1 i))) ((> i n))
    (do ((j i (add1 j))) ((> (+ i j) n))
      (do ((k j (add1 k))) ((> (+ i j k) n))
        (when (and (= (+ (* i i) (* j j)) (* k k))
                   (= (+ i j k) n))
          (display (* i j k))
          (newline)
          (exit))))))

(main 1000)
